# automatically generated by `glob_sources()`
set(
    SOURCES
    include/test-util/assert_macro_eq.h
    include/test-util/assert_type_eq.h
    lex/character_literal.cpp
    lex/single_tokens.cpp
    lex/stray_characters.cpp
    lex/unicode_characters.cpp
    util/context_value.cpp
    util/match.cpp
    util/table.cpp
    util/type_name.cpp
    PARENT_SCOPE
)
