# automatically generated by `glob_sources()`
set(
    SOURCES
    include/test-util/assert_macro_eq.h
    include/test-util/assert_type_eq.h
    util/match.cpp
    util/pp_seq.cpp
    util/record.cpp
    util/table.cpp
    util/type_name.cpp
    PARENT_SCOPE
)
